Normalize workflow compatibility for attack preparation.

diff --git a/.github/workflows/do_not_merge.yml b/.github/workflows/do_not_merge.yml
--- a/.github/workflows/do_not_merge.yml
+++ b/.github/workflows/do_not_merge.yml
@@ -1,17 +1,23 @@
 name: Do Not Merge
-
-on:
+'on':
   pull_request:
-    types: [synchronize, opened, reopened, labeled, unlabeled]
-
+    types:
+    - synchronize
+    - opened
+    - reopened
+    - labeled
+    - unlabeled
 jobs:
   do-not-merge:
     if: ${{ contains(github.event.*.labels.*.name, 'DNM') }}
     name: Prevent Merging
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-latest
     steps:
-      - name: Check for label
-        run: |
-          echo "Pull request is labeled as 'DNM'"
-          echo "This workflow fails so that the pull request cannot be merged"
-          exit 1
+    - name: Check for label
+      run: 'echo "Pull request is labeled as ''DNM''"
+
+        echo "This workflow fails so that the pull request cannot be merged"
+
+        exit 1
+
+        '
